# Generated by Django 4.0 on 2021-12-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastweb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webimg', models.ImageField(default='', upload_to='pastwebmedia/webimg/', verbose_name='Website Image')),
                ('webtitle', models.CharField(default='', max_length=200, verbose_name='Website Title')),
                ('webbody', models.TextField(default='', verbose_name='Website Body')),
                ('weburl', models.URLField(default='', verbose_name='Website Url')),
            ],
        ),
    ]
