# Generated by Django 4.0 on 2022-02-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastweb',
            name='construction',
            field=models.BooleanField(default='True', verbose_name='Under construction'),
        ),
    ]
