# Generated by Django 4.0 on 2021-12-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastweb', '0002_alter_pastweb_website image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastweb',
            name='Website Body',
        ),
        migrations.RemoveField(
            model_name='pastweb',
            name='Website Image',
        ),
        migrations.RemoveField(
            model_name='pastweb',
            name='Website Title',
        ),
        migrations.RemoveField(
            model_name='pastweb',
            name='Website Url',
        ),
        migrations.AddField(
            model_name='pastweb',
            name='webbody',
            field=models.TextField(default='', verbose_name='Website Body'),
        ),
        migrations.AddField(
            model_name='pastweb',
            name='webimg',
            field=models.ImageField(default='', upload_to='pastwebmedia/webimg/', verbose_name='Website Image'),
        ),
        migrations.AddField(
            model_name='pastweb',
            name='webtitle',
            field=models.CharField(default='', max_length=200, verbose_name='Website Title'),
        ),
        migrations.AddField(
            model_name='pastweb',
            name='weburl',
            field=models.URLField(default='', verbose_name='Website Url'),
        ),
    ]
