# Generated by Django 4.0 on 2021-12-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Bedrijfsnaam')),
                ('logo', models.ImageField(default='', upload_to='homepagemedia/logo/', verbose_name='Logo')),
                ('background', models.ImageField(default='', upload_to='homepagemedia/background/', verbose_name='Achtergrond')),
                ('introtext', models.TextField(default='', verbose_name='Intro')),
            ],
        ),
    ]
