# Generated by Django 4.0 on 2021-12-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Homepage Logo', models.ImageField(upload_to='')),
                ('Background Image', models.ImageField(upload_to='')),
                ('Homepage Intro', models.TextField()),
            ],
        ),
    ]
