# Generated by Django 4.0 on 2021-12-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_home_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='Background Image',
            field=models.ImageField(upload_to='homepagemedia/background/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Homepage Logo',
            field=models.ImageField(upload_to='homepagemedia/logo/'),
        ),
    ]
