# Generated by Django 4.0 on 2021-12-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_homepage_background image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='Name Company',
            field=models.CharField(default='Test2Impress', max_length=200),
        ),
    ]
