# Generated by Django 4.0 on 2021-12-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_homepage_name company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='Name Company',
            field=models.CharField(default='', max_length=200),
        ),
    ]
