# Generated by Django 4.0 on 2021-12-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_homepage_name company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='Name Company',
        ),
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='Bedrijf', max_length=200),
        ),
    ]
