# Generated by Django 4.0 on 2021-12-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_homepage_name company_homepage_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='Background Image',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='Homepage Intro',
            new_name='introtext',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='Homepage Logo',
            new_name='logo',
        ),
    ]
