# Generated by Django 4.0 on 2021-12-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_rename_background image_homepage_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='Bedrijf', max_length=200, verbose_name='Bedrijfsnaam'),
        ),
    ]
