# Generated by Django 4.0 on 2021-12-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_homepage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='background',
            field=models.ImageField(upload_to='homepagemedia/background/', verbose_name='Achtergrond'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='introtext',
            field=models.TextField(verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(upload_to='homepagemedia/logo/', verbose_name='Logo'),
        ),
    ]
