# Generated by Django 4.0 on 2021-12-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Who',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='')),
                ('First Name', models.CharField(max_length=200)),
                ('Last Name', models.CharField(max_length=200)),
                ('Date of Birth', models.DateField()),
                ('Who am I', models.TextField()),
                ('Cerftifications', models.TextField()),
            ],
        ),
    ]
