# Generated by Django 4.0 on 2021-12-21 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Who',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoimage', models.ImageField(default='', upload_to='whomedia/whoimage/', verbose_name='Photo')),
                ('whofirstname', models.CharField(default='', max_length=200, verbose_name='First Name')),
                ('wholastname', models.CharField(default='', max_length=200, verbose_name='Last Name')),
                ('whodob', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth')),
                ('whobody', models.TextField(default='', verbose_name='Who am I')),
                ('whocertifications', models.TextField(default='', verbose_name='Cerftifications')),
            ],
        ),
    ]
