# Generated by Django 4.0 on 2022-01-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who', '0002_who_whoaddress_who_whoemail_who_whophone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who',
            name='whoemail',
            field=models.CharField(default='', max_length=200, verbose_name='e-mailaddress'),
        ),
        migrations.AlterField(
            model_name='who',
            name='whophone',
            field=models.CharField(default='+32 (0) ', max_length=200, verbose_name='Tel nr'),
        ),
    ]
