# Generated by Django 4.0 on 2021-12-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who', '0002_alter_who_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='who',
            name='Cerftifications',
        ),
        migrations.RemoveField(
            model_name='who',
            name='Date of Birth',
        ),
        migrations.RemoveField(
            model_name='who',
            name='First Name',
        ),
        migrations.RemoveField(
            model_name='who',
            name='Last Name',
        ),
        migrations.RemoveField(
            model_name='who',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='who',
            name='Who am I',
        ),
        migrations.AddField(
            model_name='who',
            name='whobody',
            field=models.TextField(default='', verbose_name='Who am I'),
        ),
        migrations.AddField(
            model_name='who',
            name='whocertifications',
            field=models.TextField(default='', verbose_name='Cerftifications'),
        ),
        migrations.AddField(
            model_name='who',
            name='whodob',
            field=models.DateField(default='', verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='who',
            name='whofirstname',
            field=models.CharField(default='', max_length=200, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='who',
            name='whoimage',
            field=models.ImageField(default='', upload_to='whomedia/whoimage/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='who',
            name='wholastname',
            field=models.CharField(default='', max_length=200, verbose_name='Last Name'),
        ),
    ]
