# Generated by Django 4.0 on 2022-01-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who', '0003_alter_who_whoemail_alter_who_whophone'),
    ]

    operations = [
        migrations.AddField(
            model_name='who',
            name='whocv',
            field=models.FileField(default='', upload_to='whomedia/wocv/', verbose_name='Curriculum Vitae'),
        ),
    ]
