# Generated by Django 4.0 on 2021-12-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who', '0003_remove_who_cerftifications_remove_who_date of birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who',
            name='whodob',
            field=models.DateField(default='1982-10-28', verbose_name='Date of Birth'),
        ),
    ]
