# Generated by Django 4.0 on 2021-12-21 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasttest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimg', models.ImageField(default='', upload_to='pasttestmedia/projimage/', verbose_name='Project Image')),
                ('testtitle', models.CharField(default='', max_length=200, verbose_name='Project Title')),
                ('teststart', models.DateField(default=django.utils.timezone.now, verbose_name='Project Start')),
                ('testend', models.DateField(default=django.utils.timezone.now, verbose_name='Project End')),
                ('testbody', models.TextField(default='', verbose_name='Project Body')),
                ('testquotes', models.TextField(default='', verbose_name='Project Quotes')),
            ],
        ),
    ]
