# Generated by Django 4.0 on 2021-12-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasttest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project Image', models.ImageField(upload_to='')),
                ('Project Title', models.CharField(max_length=200)),
                ('Project Start', models.DateField()),
                ('Project End', models.DateField()),
                ('Project Body', models.TextField()),
                ('Project Quotes', models.TextField()),
            ],
        ),
    ]
