# Generated by Django 4.0 on 2021-12-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasttest', '0002_alter_pasttest_project image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasttest',
            name='Project Body',
        ),
        migrations.RemoveField(
            model_name='pasttest',
            name='Project End',
        ),
        migrations.RemoveField(
            model_name='pasttest',
            name='Project Image',
        ),
        migrations.RemoveField(
            model_name='pasttest',
            name='Project Quotes',
        ),
        migrations.RemoveField(
            model_name='pasttest',
            name='Project Start',
        ),
        migrations.RemoveField(
            model_name='pasttest',
            name='Project Title',
        ),
        migrations.AddField(
            model_name='pasttest',
            name='testbody',
            field=models.TextField(default='', verbose_name='Project Body'),
        ),
        migrations.AddField(
            model_name='pasttest',
            name='testend',
            field=models.DateField(default='01/02/2021', verbose_name='Project End'),
        ),
        migrations.AddField(
            model_name='pasttest',
            name='testimg',
            field=models.ImageField(default='', upload_to='pasttestmedia/projimage/', verbose_name='Project Image'),
        ),
        migrations.AddField(
            model_name='pasttest',
            name='testquotes',
            field=models.TextField(default='', verbose_name='Project Quotes'),
        ),
        migrations.AddField(
            model_name='pasttest',
            name='teststart',
            field=models.DateField(default='01/01/2021', verbose_name='Project Start'),
        ),
        migrations.AddField(
            model_name='pasttest',
            name='testtitle',
            field=models.CharField(default='', max_length=200, verbose_name='Project Title'),
        ),
    ]
