# Generated by Django 4.0 on 2021-12-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasttest', '0002_alter_pasttest_testbody_alter_pasttest_testend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasttest',
            name='testquotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
