# Generated by Django 4.0 on 2021-12-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasttest', '0003_remove_pasttest_project body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasttest',
            name='testend',
            field=models.DateField(default='2021-02-01', verbose_name='Project End'),
        ),
        migrations.AlterField(
            model_name='pasttest',
            name='teststart',
            field=models.DateField(default='2021-01-01', verbose_name='Project Start'),
        ),
    ]
