# Generated by Django 4.0 on 2021-12-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='What',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatimage', models.ImageField(default='', upload_to='whatmedia/whatimage/', verbose_name='What Image')),
                ('whattitle', models.CharField(default='', max_length=200, verbose_name='What Title')),
                ('whatbody', models.TextField(default='', verbose_name='What Body')),
            ],
        ),
    ]
