# Generated by Django 4.0 on 2021-12-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='What',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('What Image', models.ImageField(upload_to='')),
                ('What Title', models.CharField(max_length=200)),
                ('What Body', models.TextField()),
            ],
        ),
    ]
