# Generated by Django 4.0 on 2021-12-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what', '0002_alter_what_what image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='what',
            name='What Body',
        ),
        migrations.RemoveField(
            model_name='what',
            name='What Image',
        ),
        migrations.RemoveField(
            model_name='what',
            name='What Title',
        ),
        migrations.AddField(
            model_name='what',
            name='whatbody',
            field=models.TextField(default='', verbose_name='What Body'),
        ),
        migrations.AddField(
            model_name='what',
            name='whatimage',
            field=models.ImageField(default='', upload_to='whatmedia/whatimage/', verbose_name='What Image'),
        ),
        migrations.AddField(
            model_name='what',
            name='whattitle',
            field=models.CharField(default='', max_length=200, verbose_name='What Title'),
        ),
    ]
